'use strict';
/**
 * Rebuild one session's whole conversation as markdown.
 *
 * The transcript is the single source of truth, so this is idempotent: running
 * it again simply reproduces the file. That is what lets a session recorded
 * before mdserve was installed be imported after the fact, and what makes the
 * Stop hook safe to fire as often as it likes.
 *
 * Port of the original mdserve-extract.sh (bash + jq), behaviour for behaviour.
 */

const fs = require('fs');
const path = require('path');

const { sessionsDir } = require('./paths');

/** Exit-code vocabulary, shared with the hook. */
const OK = 0;
const FAILED = 1;      // nothing usable in the transcript (or it is still settling)
const BAD_INPUT = 2;   // missing file, or an id that is not a single path segment
const UNCHANGED = 3;   // rebuilt conversation is identical to the file on disk

/* ------------------------------------------------------------------ *
 * Transcript -> turns
 * ------------------------------------------------------------------ */

const trim = (s) => s.replace(/^\s+/, '').replace(/\s+$/, '');

/**
 * Prompts reach the model wrapped in machinery the reader never typed.
 * Stripping it is what makes the rendered conversation read like a
 * conversation rather than like a protocol dump.
 */
function stripNoise(text) {
  return trim(
    text
      .replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '')
      .replace(/<command-message>[\s\S]*?<\/command-message>/g, '')
      .replace(/<local-command-stdout>[\s\S]*?<\/local-command-stdout>/g, '')
      .replace(/<local-command-stderr>[\s\S]*?<\/local-command-stderr>/g, '')
      .replace(/<\/?command-(name|args|contents)>/g, '')
      .replace(/Caveat: The messages below were generated by the user[^\n]*/g, '')
      // The turn marker is ours alone: a transcript that happens to contain one
      // must not be able to forge a turn boundary in the output.
      .replace(/<!--mdsv/g, '<!-- mdsv')
  );
}

/** Prose only. Tool calls, tool results and thinking blocks are not text. */
function textOf(entry) {
  const content = entry?.message?.content;
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content
    .filter((b) => b && b.type === 'text')
    .map((b) => b.text)
    .join('\n\n');
}

/** A typed prompt carries text; a tool result carries only tool_result blocks. */
function isPrompt(entry) {
  if (entry.type !== 'user' || entry.isMeta === true) return false;
  const content = entry?.message?.content;
  if (typeof content === 'string') return true;
  return Array.isArray(content) && content.some((b) => b && b.type === 'text');
}

/**
 * Parse JSONL leniently.
 *
 * A transcript is appended to while we read it, so the final line is regularly
 * half-written. Skipping unparseable lines keeps one torn line from discarding
 * an entire conversation; `settled` reports whether the *last* line parsed, so
 * the caller can decide to wait rather than publish a turn that is still
 * arriving.
 */
function parseTranscript(raw) {
  const lines = raw.split('\n').filter((l) => l.trim() !== '');
  const entries = [];
  let settled = true;

  lines.forEach((line, i) => {
    try {
      entries.push(JSON.parse(line));
    } catch {
      if (i === lines.length - 1) settled = false;
    }
  });

  return { entries, settled };
}

/**
 * Fold the transcript into alternating user/assistant blocks.
 * Returns null when there is no prose at all in the session.
 */
function buildConversation(entries) {
  // Sub-agents run their own conversations; they are not this one.
  const all = entries.filter((e) => e.isSidechain !== true);

  const messages = [];
  for (const e of all) {
    const isAssistant = e.type === 'assistant';
    if (!isAssistant && !isPrompt(e)) continue;

    const text = stripNoise(textOf(e));
    if (text === '') continue;

    messages.push({ role: isAssistant ? 'a' : 'u', ts: e.timestamp || '', text });
  }

  // One turn can span several entries, because prose is split around tool
  // calls; fold each run of same-role entries back into a single block.
  const turns = [];
  for (const m of messages) {
    const last = turns[turns.length - 1];
    if (last && last.role === m.role) last.text += '\n\n' + m.text;
    else turns.push({ ...m });
  }

  if (turns.length === 0) return null;

  const lastOf = (pick) => {
    let found = '';
    for (const e of all) {
      const v = pick(e);
      if (v !== undefined && v !== null) found = v;
    }
    return found;
  };

  return {
    text: turns.map((t) => `<!--mdsv ${t.role} ${t.ts}-->\n\n${t.text}`).join('\n\n'),
    turns: turns.length,
    title: lastOf((e) => (e.type === 'ai-title' ? e.aiTitle : undefined)) || '',
    prompt: lastOf((e) => (e.type === 'last-prompt' ? e.lastPrompt : undefined)) || '',
    cwd: lastOf((e) => (e.cwd !== null && e.cwd !== undefined ? e.cwd : undefined)) || '',
  };
}

/** What the session menu shows, in order of preference. */
function sidecarTitle({ title, prompt, cwd }) {
  if (title.length > 0) return title;
  if (prompt.length > 0) return [...prompt].slice(0, 70).join('');
  return cwd.split('/').pop() || 'session';
}

/* ------------------------------------------------------------------ *
 * Entry point
 * ------------------------------------------------------------------ */

/**
 * @param {string} transcript  path to <session>.jsonl
 * @param {{dir?: string, requireChange?: boolean}} [opts]
 * @returns {{code: number, session?: string}}
 */
function extract(transcript, opts = {}) {
  const dir = opts.dir || sessionsDir();
  const requireChange = opts.requireChange ?? false;

  if (!transcript || !fs.existsSync(transcript) || !fs.statSync(transcript).isFile()) {
    return { code: BAD_INPUT };
  }

  // The transcript is named after the session it records. Keep the id to a
  // single path segment: it becomes a filename and, later, a URL parameter.
  const session = path.basename(transcript, '.jsonl');
  if (!/^[A-Za-z0-9._-]+$/.test(session)) return { code: BAD_INPUT };

  let raw;
  try {
    raw = fs.readFileSync(transcript, 'utf8');
  } catch {
    return { code: FAILED };
  }

  const { entries, settled } = parseTranscript(raw);

  // A torn final line means the turn is still being written. The hook polls on
  // this: better to retry than to publish a conversation missing its last word.
  if (!settled && requireChange) return { code: FAILED };
  if (entries.length === 0) return { code: FAILED };

  const info = buildConversation(entries);
  if (!info) return { code: FAILED };

  fs.mkdirSync(dir, { recursive: true });
  const file = path.join(dir, session + '.md');

  // Lets the hook tell "the turn has not landed yet" apart from "nothing new".
  if (requireChange && fs.existsSync(file)) {
    let current = '';
    try {
      current = fs.readFileSync(file, 'utf8');
    } catch {
      current = '';
    }
    if (info.text === current.replace(/\n+$/, '')) return { code: UNCHANGED, session };
  }

  fs.writeFileSync(file, info.text + '\n');

  // The menu sorts by mtime, so borrow the transcript's: it dates the last
  // thing actually said, which keeps a bulk import in true chronological order.
  try {
    const src = fs.statSync(transcript);
    fs.utimesSync(file, src.atime, src.mtime);
  } catch {
    // Cosmetic only: a session that keeps its own mtime still renders fine.
  }

  fs.writeFileSync(
    path.join(dir, session + '.json'),
    JSON.stringify({ title: sidecarTitle(info), cwd: info.cwd, turns: info.turns }) + '\n'
  );

  return { code: OK, session };
}

module.exports = { extract, OK, FAILED, BAD_INPUT, UNCHANGED, stripNoise, buildConversation, parseTranscript };
